export interface Teacher {
    id: number;
    schoolId: number;
    firstName: string;
    lastName: string;
    email: string;
    phone: string;
}
export const stubTeachers: Teacher[] = [
    {
        id: 1,
        schoolId: 1,
        firstName: "Sarah",
        lastName: "Johnson",
        email: "sarah.johnson@gmail.com",
        phone: "0400123456",
    },
    {
        id: 2,
        schoolId: 2,
        firstName: "Michael",
        lastName: "Smith",
        email: "michael.smith@gmail.com",
        phone: "0401234567",
    },
    {
        id: 3,
        schoolId: 3,
        firstName: "Emily",
        lastName: "Williams",
        email: "emily.williams@gmail.com",
        phone: "0402345678",
    },
    {
        id: 4,
        schoolId: 1,
        firstName: "James",
        lastName: "Brown",
        email: "james.brown@gmail.com",
        phone: "0403456789",
    },
    {
        id: 5,
        schoolId: 2,
        firstName: "Jessica",
        lastName: "Davis",
        email: "jessica.davis@gmail.com",
        phone: "0404567890",
    },
    {
        id: 6,
        schoolId: 3,
        firstName: "Robert",
        lastName: "Miller",
        email: "robert.miller@gmail.com",
        phone: "0405678901",
    },
    {
        id: 7,
        schoolId: 1,
        firstName: "Karen",
        lastName: "Moore",
        email: "karen.moore@gmail.com",
        phone: "0406789012",
    },
    {
        id: 8,
        schoolId: 2,
        firstName: "Christopher",
        lastName: "Taylor",
        email: "christopher.taylor@gmail.com",
        phone: "0407890123",
    },
    {
        id: 9,
        schoolId: 3,
        firstName: "Elizabeth",
        lastName: "Anderson",
        email: "elizabeth.anderson@gmail.com",
        phone: "0408901234",
    },
    {
        id: 10,
        schoolId: 1,
        firstName: "David",
        lastName: "Thomas",
        email: "david.thomas@gmail.com",
        phone: "0409012345",
    },
    {
        id: 11,
        schoolId: 2,
        firstName: "Samantha",
        lastName: "Jackson",
        email: "samantha.jackson@gmail.com",
        phone: "0410123456",
    },
    {
        id: 12,
        schoolId: 3,
        firstName: "Richard",
        lastName: "White",
        email: "richard.white@gmail.com",
        phone: "0411234567",
    },
    {
        id: 13,
        schoolId: 1,
        firstName: "Ashley",
        lastName: "Harris",
        email: "ashley.harris@gmail.com",
        phone: "0412345678",
    },
    {
        id: 14,
        schoolId: 2,
        firstName: "Matthew",
        lastName: "Martin",
        email: "matthew.martin@gmail.com",
        phone: "0413456789",
    },
    {
        id: 15,
        schoolId: 3,
        firstName: "Laura",
        lastName: "Thompson",
        email: "laura.thompson@gmail.com",
        phone: "0414567890",
    },
    {
        id: 16,
        schoolId: 1,
        firstName: "John",
        lastName: "Garcia",
        email: "john.garcia@gmail.com",
        phone: "0415678901",
    },
    {
        id: 17,
        schoolId: 2,
        firstName: "Amanda",
        lastName: "Robinson",
        email: "amanda.robinson@gmail.com",
        phone: "0416789012",
    },
    {
        id: 18,
        schoolId: 3,
        firstName: "William",
        lastName: "Lewis",
        email: "william.lewis@gmail.com",
        phone: "0417890123",
    },
    {
        id: 19,
        schoolId: 1,
        firstName: "Jessica",
        lastName: "King",
        email: "jessica.king@gmail.com",
        phone: "0418901234",
    },
    {
        id: 20,
        schoolId: 2,
        firstName: "Robert",
        lastName: "Wright",
        email: "robert.wright@gmail.com",
        phone: "0419012345",
    },
];
